Module: My.Pinpoint
Version: 1.1-DEV
Description: A LambdaSharp hackathon using AWS Pinpoint
Using:

  - Module: LambdaSharp.S3.IO@lambdasharp

Items:

  - Function: SurveySms
    Description: TO-DO - update function description
    Memory: 256
    Timeout: 30
    Sources:
      - Topic: PinpointSmsTopic

  - Resource: PinpointSmsTopic
    Description: The topic that Pinpoint generates on user SMS responses
    Type: AWS::SNS::Topic
    Allow: Subscribe

  - Resource: PinpointBucket
    Type: AWS::S3::Bucket
    Allow: ReadWrite
    Scope: SurveySms

  - Resource: EmptyBucket
    Type: LambdaSharp::S3::EmptyBucket
    Properties:
      Bucket: !Ref PinpointBucket

  - Resource: PinpointPolicy
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AWS::StackName}PinpointPolicy"
      PolicyDocument:
        Id: PinpointPolicy
        Version: "2012-10-17"
        Statement:
          - Sid: PinpointMobileTargetingSendMessages
            Effect: Allow
            Action: mobiletargeting:SendMessages
            Resource: "*"
      Roles:
        - !Ref Module::Role


