# The Module Name is used as prefix for all contained resources.
Module: My.CustomerSurvey

# The Module Version is shown in the CloudFormation stack and Lambda function descriptions.
Version: 1.0-DEV

# The Module Description is shown in the AWS CloudFormation console with the version number.
Description: Module description

# The Items section defines values and resources for the module.
Items:

  - Variable: MyVariable
    Description: Variable description
    Value: A sample variable value for the module

  - Function: SurveySms
    Description: TO-DO - update function description
    Memory: 256
    Timeout: 30
    Sources:
      - Topic: PinpointSmsTopic

  - Resource: PinpointSmsTopic
    Description: The topic that Pinpoint generates on user SMS responses
    Type: AWS::SNS::Topic
    Allow: Subscribe
